### ISSUE TITLE
Package is not getting installed with react-native expo application

### ISSUE THREAD

**Issue by jigushah** [alexbrillant/react-native-deck-swiper#63] opened 2017-09-03 07:45 UTC
![screen shot 2017-09-03 at 1 14 33 pm](https://user-images.githubusercontent.com/29692329/30001373-e29da3b8-90a9-11e7-9cc3-1ff0c6222085.png)
It is stuck at this point every time.

**Comment by alexbrillant** [comment] 2017-09-03 17:18
I cannot reproduce. I don't think this is related to my package. 

Maybe this stackoverflow answer can help ? https://stackoverflow.com/questions/40874237/npm-install-hangs-on-loadrequesteddeps

I will close this issue because I don't think this is related to react-native-deck-swiper

**Closed by alexbrillant** 2017-09-03 17:18 UTC

**Comment by bnap00** [comment] 2018-01-22 13:19
Actually, this problem persists. 
Steps to reproduce: 
* Create new application with [expo](https://expo.io/learn). 
* Install react-native-deck-swiper. 
and it does not work. 

Please re-open the issue.
