### ISSUE TITLE
swipe back doesnt work

### ISSUE THREAD

**Issue by Radec43** [alexbrillant/react-native-deck-swiper#67] opened 2017-09-26 13:08 UTC
i tried to use code from App.js file from examples demo folder and swipeBack function doesn't work like i was expected to swipe one item back. Instead It swipes on first item of the cards array and when you try to swipe cards after that at the third card it does the same thing without clicking on a swipe back button

  onSwipedAllCards = () => {
    this.setState({
      swipedAllCards: true
    })
  };

  swipeBack = () => {
    if (!this.state.isSwipingBack) {
      this.setIsSwipingBack(true, () => {
        this.swiper.swipeBack(() => {
          this.setIsSwipingBack(false)
        })
      })
    }
  };

 <Button onPress={this.swipeBack} title='Swipe Back' />

And i saw that there is goBackToPreviousCardOnSwipeLeft/Right/Top/Bottom props 
but can we used that on a button click instead of swipe ?

**Comment by alexbrillant** [comment] 2017-09-26 13:52
@Radec43 duplicate of #21

**Closed by alexbrillant** 2017-09-26 13:52 UTC
