### ISSUE TITLE
Invalid width of type string supplied to overlayLabelWrapper

### ISSUE THREAD

**Issue by miclaus** [alexbrillant/react-native-deck-swiper#71] opened 2017-10-05 10:38 UTC
Happens with the basic example from [README](https://github.com/alexbrillant/react-native-deck-swiper#usage-example): 

<img width="282" alt="screen shot 2017-10-05 at 12 33 42" src="https://user-images.githubusercontent.com/4658706/31223110-8dd1ef72-a9c9-11e7-99b4-586a45f07284.png">

Props `width` and `height` shouldn't be of type string as described here:
https://github.com/alexbrillant/react-native-deck-swiper#overlaylabelwrapperstyle-default-props

Wouldn't it be better to use flexbox and use `alignSelf: 'stretch'` ?

**Comment by designorant** [comment] 2017-10-05 11:30
@miclaus Which version of RN do you use? Percentages [landed early this year](https://github.com/facebook/react-native/commit/3f49e743bea730907066677c7cbfbb1260677d11).

Flexbox vs absolute positioning [have been covered](https://github.com/alexbrillant/react-native-deck-swiper/issues/4). TL;DR: There are things that are possible with absolute positioning that can't be reproduced using flexbox alone.

**Comment by miclaus** [comment] 2017-10-05 12:19
@designorant i'm using the minimum supported version specified in `package.json` that being `0.41.2`.

i tested it using `alignSelf: 'stretch'` and it worked fine for me, but i still have to figure something out for the `height` of the cards.

**Comment by designorant** [comment] 2017-10-05 12:31
@miclaus I see, apologies.

@alexbrillant Looks like we should bump RN in `package.json` to `0.42.3`. See: https://github.com/facebook/react-native/releases/tag/v0.42.3

**Comment by miclaus** [comment] 2017-10-05 12:55
@designorant no worries, thank's for the version tip, i'll give that a try.

**Comment by alexbrillant** [comment] 2017-10-05 16:56
@designorant  bumped rn peer dependencies and examples rn version in 1.4.2

**Closed by alexbrillant** 2017-10-05 16:56 UTC

**Comment by miclaus** [comment] 2017-10-17 23:51
@alexbrillant isn't that quite a high jump from the previous RN version ?
(ref https://github.com/alexbrillant/react-native-deck-swiper/commit/29e2c7ec3dda4286793b61977724fdd2472af61a#diff-b9cfc7f2cdf78a7f4b91a753d10865a2)

a minimum supported RN version should be chosen, instead of the latest – or am i mistaken ?
