### ISSUE TITLE
Position of Swiper

### ISSUE THREAD

**Issue by leon2835** [alexbrillant/react-native-deck-swiper#204] opened 2018-12-14 06:56 UTC
Hi there, let's say i want to position the swiper at a certain place, below the "Top Text" and above the "End Text" (center of it), how am i suppose to do it? It seems like i'm wrapping those text with a "View", and "Swiper" between the "Text". But the result is not expected and the swiper show in other place instead between them.
<img width="818" alt="screen shot 2018-12-14 at 2 55 12 pm" src="https://user-images.githubusercontent.com/19604759/49988013-4e6ea080-ffb0-11e8-9660-ef5aeabb39c8.png">

**Comment by rajonali** [comment] 2019-01-23 05:12
Yeah same thing is happening for me.

**Comment by dcangulo** [comment] 2019-03-13 09:27
Have you found any solution?

**Comment by webraptor** [comment] 2019-03-13 13:38
The swiper is absolutely positioned, it's intentional. You'll need to build your screens based on that. Please close this issue as it is not a bug.

**Closed** 2019-03-14 03:10 UTC

**Comment by abassey** [comment] 2022-02-26 21:00
Hi! @leon2835 were you able to figure out a workaround for this? If you were, would you be comfortable sharing it please? I am stuck on how to do it still

**Comment by OziTFA** [comment] 2023-05-23 20:56
Maybe one way is to give an absolute position to the 'end text' and set it to the bottom.
