### ISSUE TITLE
a strange issue

### ISSUE THREAD

**Issue by lzctbyong** [alexbrillant/react-native-deck-swiper#11] opened 2017-05-16 09:16 UTC
it causes a issue when i move the object , release ,and click the object quickly,
the object will stay an incorrect positon 
such as :
![20170516172246](https://cloud.githubusercontent.com/assets/17008940/26099232/b7fa77ba-3a5c-11e7-9ee6-1eb06eb0c475.png)

**Comment by lzctbyong** [comment] 2017-05-16 09:28
By the way , Thank you for the nice comonpent

**Comment by lzctbyong** [comment] 2017-05-16 09:49
Can move right it increases and move left it decreases?

**Comment by alexbrillant** [comment] 2017-05-16 12:19
Are you using the latest version of RN? I cannot reproduce with react-native v >= 0.43.3.

**Comment by alexbrillant** [comment] 2017-05-16 12:20
I have seen this issue before with a previous version of RN, but I can't remember witch one it is.

**Comment by lzctbyong** [comment] 2017-05-16 12:21
@alexbrillant RN 0.44

**Comment by alexbrillant** [comment] 2017-05-16 12:22
@lzctbyong Does this bug occur only on android?

**Comment by lzctbyong** [comment] 2017-05-16 12:29
@alexbrillant  My Platform is Android,  I have not test IOS  ,I guess it's an  issue about PanResponder 
Do you have this issue?

**Comment by alexbrillant** [comment] 2017-05-16 12:35
@lzctbyong  Are you using the latest version of this package (1.1.6) ?

**Comment by alexbrillant** [comment] 2017-05-16 12:43
@lzctbyong  I haven't tested it on 0.44 yet, and I cannot reproduce the bug on my current test project. I will try to find time today to test it. I think that using updateNativeStyles() instead of Animated.Event could do the trick. This is what they use in the example. A pull request would be cool. https://facebook.github.io/react-native/docs/panresponder.html

**Comment by lzctbyong** [comment] 2017-05-16 12:53
@alexbrillant  it's latest (1.1.6), I  try to find more information about the issue  for you

**Comment by lzctbyong** [comment] 2017-05-16 13:30
i find the code for the issue:

`  
onPanResponderGrant = ( event , gestureState ) => {
        console.log('Swiper(93):::onPanResponderGrant---->',)
        this.state.pan.setOffset( {
            x: this._animatedValueX ,
            y: this._animatedValueY
        } )
        this.state.pan.setValue( {
            x: 0 ,
            y: 0
        } )
    }
`
if the code likes this ,it would be OK

`
this.state.pan.setOffset( {
            x: 0,
            y: 0
 } ) 
`
What do you think about it ??

**Comment by alexbrillant** [comment] 2017-05-16 15:03
@lzctbyong thanks for the help. if you want to be a contributor, you can fork my repo, and submit a pull request. Otherwise, I will test it out tonight, and publish it if it works

**Comment by alexbrillant** [comment] 2017-05-16 23:19
Cannot reproduce in ios

**Comment by lzctbyong** [comment] 2017-05-17 01:26
@alexbrillant So Funny , I would test the iOS Platform when I'm free

**Comment by alexbrillant** [comment] 2017-05-17 03:27
@lzctbyong  Cannot reproduce on android either.

**Comment by alexbrillant** [comment] 2017-05-17 03:28
I will close this issue. Please verify that your project is using the latest version of my package, and of react native : 

react-native-cli: 2.0.1
react-native: 0.44.0
react-native-deck-swiper 1.1.6

**Comment by alexbrillant** [comment] 2017-05-17 03:34
Ohh, I get it now. You have to tap really quick on the element while it is being swiped haha. Okey, I think I know how to fix this !

**Comment by lzctbyong** [comment] 2017-05-17 03:36
@alexbrillant Right! you found it finally

**Comment by alexbrillant** [comment] 2017-05-17 03:42
Thanks ! I'm sorry I couldn't understand your issue before :p

**Comment by lzctbyong** [comment] 2017-05-17 03:47
My English is poor , so that I can't describe the details too much . 
It's not your problem ,You can close the issue after you fix it .

**Comment by alexbrillant** [comment] 2017-05-17 05:34
@lzctbyong fixed in v1.1.7 ! 👍

**Closed by alexbrillant** 2017-05-17 05:34 UTC
Labels: bug
