### ISSUE TITLE
Cards not resetting to the initial position

### ISSUE THREAD

**Issue by pallavbakshi** [alexbrillant/react-native-deck-swiper#93] opened 2017-12-12 08:46 UTC
Hi,

While swiping the cards, sometimes the upcoming card doesn't render at its original position and remains a little bit off from its supposed position. Here are two pictures to support the claim. Is there any way to fix it?

![h11](https://user-images.githubusercontent.com/15682249/33875090-16c41cb2-df47-11e7-8e9e-086d2bda784d.png)

![hi2](https://user-images.githubusercontent.com/15682249/33875043-ecfbec5c-df46-11e7-83a4-295668a7462d.png)

**Comment by alexbrillant** [comment] 2017-12-13 04:11
what rn version are you using ?

**Comment by pallavbakshi** [comment] 2017-12-13 06:42
@alexbrillant Hey, I am using 
        "prop-types": "^15.5.10",
   	"react": "16.0.0",
    	"react-native": "0.50.4",
        "react-native-deck-swiper": "^1.4.4"

**Comment by webraptor** [comment] 2017-12-14 21:54
We've experienced this in the past as well, but only after a behaviour that we catalogued as, erratic. We only experienced this if we heavily used the pan function going with the card fast from one area to another and finally releasing it in a random position. During regular swipes it has never happened.

**Comment by pallavbakshi** [comment] 2017-12-15 06:23
Hey @webraptor , thanks for the tip. I totally agree with your comment. Card displacement happens only if I swipe like crazy. However, don't you think it is a bug since it shouldn't depend upon the frequency or the way I swipe the cards. If you used the component in its current form then have you gotten any user complaints regarding this issue?

**Comment by webraptor** [comment] 2017-12-15 06:44
None whatsoever. We only replicated this during development and intense QA ...

**Comment by alexbrillant** [comment] 2017-12-26 21:41
closing this issue for now thanks

**Closed by alexbrillant** 2017-12-26 21:41 UTC

**Comment by pallavbakshi** [comment] 2017-12-27 05:59
Message for anyone having same issue:
I didn't find a fix. But as webraptor and I observed that it only happens if you rigorously swipe the cards so this issue is not a big deal. However, it is still a bug (according to me). And if anyone in the future fixes it then please link the fork in the comments or send a PR to the author. Thank you! And huge thanks to @alexbrillant for making it available to all of us.

**Comment by abdymm** [comment] 2021-03-25 04:07
hi @pallavbakshi @alexbrillant is this issue already fix?

**Comment by clycheng2015** [comment] 2021-03-30 05:08
> Message for anyone having same issue:
> I didn't find a fix. But as webraptor and I observed that it only happens if you rigorously swipe the cards so this issue is not a big deal. However, it is still a bug (according to me). And if anyone in the future fixes it then please link the fork in the comments or send a PR to the author. Thank you! And huge thanks to @alexbrillant for making it available to all of us.

hi，I miss the same issies when I swipe to top fastly like crazy! I do not thnow what happen! at start! I think it caused by too frequently rerender! I try to change state with mobx ,but not work!

**Comment by clycheng2015** [comment] 2021-03-30 05:10
> hi @pallavbakshi @alexbrillant is this issue already fix?

do you miss the same propblem?already fix??

**Comment by clycheng2015** [comment] 2021-03-30 05:10
> hi @pallavbakshi @alexbrillant is this issue already fix?

do you miss the same propblem?already fix??

**Comment by clycheng2015** [comment] 2021-03-30 05:13
> hi @pallavbakshi @alexbrillant is this issue already fix?

do you miss the same propblem?already fix??

**Comment by abdymm** [comment] 2021-03-30 05:15
hi @clycheng2015 i found some solution on this, but don't know if this a real solution, but in mine even i fast swipe it will always go to the initial position, on `Swiper.js` you can try to remove these lines, i see these lines was add some offset on the x,y position, so i just remove it, and no more tilted card 
```
    if (!this.state.panResponderLocked) {
       this.state.pan.setOffset({
         x: this._animatedValueX,
         y: this._animatedValueY,
       })
    }
```

please try on your end, and confirm here

**Comment by clycheng2015** [comment] 2021-03-30 05:17
> hi @pallavbakshi @alexbrillant is this issue already fix?

do you miss the same propblem?already fix??

> hi @clycheng2015 i found some solution on this, but don't know if this a real solution, but in mine even i fast swipe it will always go to the initial position, on `Swiper.js` you can try to remove these lines, i see these lines was add some offset on the x,y position, so i just remove it, and no more tilted card
> 
> ```
>     if (!this.state.panResponderLocked) {
>        this.state.pan.setOffset({
>          x: this._animatedValueX,
>          y: this._animatedValueY,
>        })
>     }
> ```
> 
> please try on your end, and confirm here

thank you for your tip!let me try!

**Comment by clycheng2015** [comment] 2021-03-30 05:24
> > hi @pallavbakshi @alexbrillant is this issue already fix?
> 
> do you miss the same propblem?already fix??
> 
> > hi @clycheng2015 i found some solution on this, but don't know if this a real solution, but in mine even i fast swipe it will always go to the initial position, on `Swiper.js` you can try to remove these lines, i see these lines was add some offset on the x,y position, so i just remove it, and no more tilted card
> > ```
> >     if (!this.state.panResponderLocked) {
> >        this.state.pan.setOffset({
> >          x: this._animatedValueX,
> >          y: this._animatedValueY,
> >        })
> >     }
> > ```
> > 
> > 
> > please try on your end, and confirm here
> 
> thank you for your tip!let me try!

yes, It fix! thank you@pallavbakshi!It's been bothering me for a long time！and  tried a lot of ways to change but not resolve!

**Comment by abdymm** [comment] 2021-03-30 05:45
hi @clycheng2015 sure no worries, and iam @abdymm  not @pallavbakshi  hahaha
